[package]
name = "test_sqlite_perf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
rusqlite = "0.31.0"
log = "0.4.22"
smol_str = "0.2.2"
uuid = { version = "1.10.0", features = ["v4"] }
